# Generated by Django 5.0.9 on 2024-10-08 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_tags_recipe_cuisinetype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cuisineType',
        ),
    ]
