# Generated by Django 5.0.9 on 2024-10-08 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_recipe_cuisinetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cuisineType',
            field=models.CharField(choices=[('AF', 'African'), ('US', 'American'), ('CA', 'CentralAmerican'), ('SA', 'SouthAmerican'), ('C', 'Caribbean'), ('AS', 'Asian'), ('EU', 'European'), ('O', 'Other')], default='O', max_length=2),
        ),
    ]
